export const ADD_TOKEN = 'ADD_TOKEN';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";

export const FETCH_INGREDIENTS_START = "FETCH_INGREDIENTS_START";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGREDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_ERROR = "FETCH_INGREDIENTS_ERROR";

export const CREATE_RECIPE = "CREATE_RECIPE";
export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_MY_RECIPES = "FETCH_MY_RECIPES";
export const EDIT_MY_RECIPE = "EDIT_MY_RECIPE";
export const ADD_INGREDIENT_TO_RECIPE = "ADD_INGREDIENT_TO_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";

export const CREATE_MEAL = "CREATE_MEAL";
export const FETCH_MEALS = "FETCH_MEALS";
export const EDIT_MEAL = "DIT_MEAL";
export const DELETE_MEAL = "DELETE_MEAL";
export const DELETE_RECIPE_IN_MEAL = "DELETE_RECIPE_IN_MEAL";

export const ADD_INGREDIENT_TO_PANTRY = "ADD_INGREDIENT_TO_PANTRY";
export const FETCH_PANTRY_INGREDIENTS = "FETCH_PANTRY_INGREDIENTS";
export const DELETE_PANTRY_INGREDIENT = "DELETE_PANTRY_INTGREDIENT";

export const CREATE_MEALPLAN = "CREATE_MEALPLAN";
export const FETCH_MEALPLANS = "FETCH_MEALPLANS";
export const EDIT_MEAL_PLAN = "EDIT_MEAL_PLAN ";
export const DELETE_MEALPLAN = "DELETE_MEALPLAN";
export const FETCH_GROCERY_LIST = "FETCH_GROCERY_LIST";
